### ISSUE TITLE
No check on spaces in model name

### ISSUE THREAD

**Issue by delagela** [UndergroundFPV/opentx-nv14-ufpv#4]
You can put spaces on model names, but if you do so, there is no way to revert it.

**Comment by lococnc** [comment]
I can verify this, Once a space is inserted, anywhere (not just the model name, applies to any text field entry), if you edit the name you cannot remove the space because you cannot select to the right of the space, therefore no way to use the backspace button to erase, even if there is regular alpha text following, you cannot select that either.
